rpm_info_list ='''bash                                  x86_64           4.4.19-12.el8                                rhel-basos               1.5 M
 bzip2                                 x86_64           1.0.6-26.el8                                 rhel-basos                60 k
 coreutils                             x86_64           8.30-8.el8                                   rhel-basos               1.2 M
 cpio                                  x86_64           2.12-8.el8                                   rhel-basos               265 k
 diffutils                             x86_64           3.6-6.el8                                    rhel-basos               359 k
 findutils                             x86_64           1:4.6.0-20.el8                               rhel-basos               528 k
 gawk                                  x86_64           4.2.1-1.el8                                  rhel-basos               1.1 M
 gcc                                   x86_64           8.3.1-5.1.el8                                rhel-appstream            23 M
 gcc-c++                               x86_64           8.3.1-5.1.el8                                rhel-appstream            12 M
 gnupg2                                x86_64           2.2.20-2.el8                                 rhel-basos               2.4 M
 grep                                  x86_64           3.1-6.el8                                    rhel-basos               274 k
 gzip                                  x86_64           1.9-9.el8                                    rhel-basos               167 k
 info                                  x86_64           6.5-6.el8                                    rhel-basos               198 k
 make                                  x86_64           1:4.2.1-10.el8                               rhel-basos               498 k
 patch                                 x86_64           2.7.6-11.el8                                 rhel-basos               138 k
 redhat-rpm-config                     noarch           123-1.el8                                    rhel-appstream            84 k
 rpm-build                             x86_64           4.14.3-4.el8                                 rhel-appstream           172 k
 scl-utils-build                       x86_64           1:2.0.2-12.el8                               rhel-appstream            26 k
 sed                                   x86_64           4.5-2.el8                                    rhel-basos               298 k
 shadow-utils                          x86_64           2:4.6-11.el8                                 rhel-basos               1.2 M
 tar                                   x86_64           2:1.30-5.el8                                 rhel-basos               838 k
 unzip                                 x86_64           6.0-43.el8                                   rhel-basos               195 k
 util-linux                            x86_64           2.32.1-24.el8                                rhel-basos               2.5 M
 which                                 x86_64           2.21-12.el8                                  rhel-basos                49 k
 acl                                   x86_64           2.2.53-1.el8                                 rhel-basos                81 k
 annobin                               x86_64           9.23-1.el8                                   rhel-appstream           104 k
 audit-libs                            x86_64           3.0-0.17.20191104git1c2f876.el8              rhel-basos               116 k
 basesystem                            noarch           11-5.el8                                     rhel-basos                11 k
 binutils                              x86_64           2.30-79.el8                                  rhel-basos               5.7 M
 brotli                                x86_64           1.0.6-2.el8                                  rhel-basos               322 k
 bzip2-libs                            x86_64           1.0.6-26.el8                                 rhel-basos                48 k
 ca-certificates                       noarch           2020.2.41-80.0.el8_2                         rhel-basos               391 k
 chkconfig                             x86_64           1.13-2.el8                                   rhel-basos               194 k
 coreutils-common                      x86_64           8.30-8.el8                                   rhel-basos               2.0 M
 cpp                                   x86_64           8.3.1-5.1.el8                                rhel-appstream            10 M
 cracklib                              x86_64           2.9.6-15.el8                                 rhel-basos                93 k
 crypto-policies                       noarch           20200713-1.git51d1222.el8                    rhel-basos                62 k
 cryptsetup-libs                       x86_64           2.3.3-2.el8                                  rhel-basos               470 k
 curl                                  x86_64           7.61.1-14.el8                                rhel-basos               353 k
 cyrus-sasl-lib                        x86_64           2.1.27-5.el8                                 rhel-basos               123 k
 dbus                                  x86_64           1:1.12.8-11.el8                              rhel-basos                41 k
 dbus-common                           noarch           1:1.12.8-11.el8                              rhel-basos                45 k
 dbus-daemon                           x86_64           1:1.12.8-11.el8                              rhel-basos               240 k
 dbus-libs                             x86_64           1:1.12.8-11.el8                              rhel-basos               183 k
 dbus-tools                            x86_64           1:1.12.8-11.el8                              rhel-basos                85 k
 device-mapper                         x86_64           8:1.02.171-5.el8                             rhel-basos               373 k
 device-mapper-libs                    x86_64           8:1.02.171-5.el8                             rhel-basos               406 k
 dracut                                x86_64           049-95.git20200804.el8                       rhel-basos               367 k
 dwz                                   x86_64           0.12-9.el8                                   rhel-appstream           109 k
 efi-srpm-macros                       noarch           3-2.el8                                      rhel-appstream            22 k
 elfutils                              x86_64           0.180-1.el8                                  rhel-basos               542 k
 elfutils-default-yama-scope           noarch           0.180-1.el8                                  rhel-basos                49 k
 elfutils-libelf                       x86_64           0.180-1.el8                                  rhel-basos               215 k
 elfutils-libs                         x86_64           0.180-1.el8                                  rhel-basos               293 k
 expat                                 x86_64           2.2.5-4.el8                                  rhel-basos               111 k
 file                                  x86_64           5.33-16.el8                                  rhel-basos                76 k
 file-libs                             x86_64           5.33-16.el8                                  rhel-basos               542 k
 filesystem                            x86_64           3.8-3.el8                                    rhel-basos               1.1 M
 gc                                    x86_64           7.6.4-3.el8                                  rhel-appstream           109 k
 gdb-headless                          x86_64           8.2-12.el8                                   rhel-appstream           3.7 M
 gdbm                                  x86_64           1:1.18-1.el8                                 rhel-basos               130 k
 gdbm-libs                             x86_64           1:1.18-1.el8                                 rhel-basos                60 k
 gettext                               x86_64           0.19.8.1-17.el8                              rhel-basos               1.1 M
 gettext-libs                          x86_64           0.19.8.1-17.el8                              rhel-basos               313 k
 ghc-srpm-macros                       noarch           1.4.2-7.el8                                  rhel-appstream           9.4 k
 glib2                                 x86_64           2.56.4-8.el8                                 rhel-basos               2.5 M
 glibc                                 x86_64           2.28-127.el8                                 rhel-basos               3.6 M
 glibc-all-langpacks                   x86_64           2.28-127.el8                                 rhel-basos                25 M
 glibc-common                          x86_64           2.28-127.el8                                 rhel-basos               1.3 M
 glibc-devel                           x86_64           2.28-127.el8                                 rhel-basos               1.0 M
 glibc-headers                         x86_64           2.28-127.el8                                 rhel-basos               475 k
 gmp                                   x86_64           1:6.1.2-10.el8                               rhel-basos               321 k
 gnutls                                x86_64           3.6.14-6.el8                                 rhel-basos               1.0 M
 go-srpm-macros                        noarch           2-16.el8                                     rhel-appstream            14 k
 grub2-common                          noarch           1:2.02-90.el8                                rhel-basos               884 k
 grub2-tools                           x86_64           1:2.02-90.el8                                rhel-basos               2.0 M
 grub2-tools-minimal                   x86_64           1:2.02-90.el8                                rhel-basos               204 k
 guile                                 x86_64           5:2.0.14-7.el8                               rhel-appstream           3.5 M
 ima-evm-utils                         x86_64           1.1-5.el8                                    rhel-basos                55 k
 iptables-libs                         x86_64           1.8.4-15.el8                                 rhel-basos               106 k
 isl                                   x86_64           0.16.1-6.el8                                 rhel-appstream           841 k
 iso-codes                             noarch           3.79-2.el8                                   rhel-appstream           3.4 M
 json-c                                x86_64           0.13.1-0.2.el8                               rhel-basos                40 k
 kbd-legacy                            noarch           2.0.4-10.el8                                 rhel-basos               481 k
 kbd-misc                              noarch           2.0.4-10.el8                                 rhel-basos               1.5 M
 kernel-headers                        x86_64           4.18.0-240.el8                               rhel-basos               5.5 M
 keyutils-libs                         x86_64           1.5.10-6.el8                                 rhel-basos                34 k
 kmod                                  x86_64           25-16.el8                                    rhel-basos               126 k
 kmod-libs                             x86_64           25-16.el8                                    rhel-basos                68 k
 krb5-libs                             x86_64           1.18.2-5.el8                                 rhel-basos               837 k
 libacl                                x86_64           2.2.53-1.el8                                 rhel-basos                35 k
 libarchive                            x86_64           3.3.2-9.el8                                  rhel-basos               358 k
 libassuan                             x86_64           2.5.1-3.el8                                  rhel-basos                83 k
 libatomic_ops                         x86_64           7.6.2-3.el8                                  rhel-appstream            38 k
 libattr                               x86_64           2.4.48-3.el8                                 rhel-basos                27 k
 libbabeltrace                         x86_64           1.5.4-3.el8                                  rhel-basos               200 k
 libblkid                              x86_64           2.32.1-24.el8                                rhel-basos               216 k
 libcap                                x86_64           2.26-4.el8                                   rhel-basos                60 k
 libcap-ng                             x86_64           0.7.9-5.el8                                  rhel-basos                33 k
 libcom_err                            x86_64           1.45.6-1.el8                                 rhel-basos                49 k
 libcroco                              x86_64           0.6.12-4.el8_2.1                             rhel-basos               113 k
 libcurl                               x86_64           7.61.1-14.el8                                rhel-basos               298 k
 libdb                                 x86_64           5.3.28-39.el8                                rhel-basos               750 k
 libdb-utils                           x86_64           5.3.28-39.el8                                rhel-basos               149 k
 libfdisk                              x86_64           2.32.1-24.el8                                rhel-basos               249 k
 libffi                                x86_64           3.1-22.el8                                   rhel-basos                37 k
 libgcc                                x86_64           8.3.1-5.1.el8                                rhel-basos                78 k
 libgcrypt                             x86_64           1.8.5-4.el8                                  rhel-basos               463 k
 libgomp                               x86_64           8.3.1-5.1.el8                                rhel-basos               204 k
 libgpg-error                          x86_64           1.31-1.el8                                   rhel-basos               242 k
 libidn2                               x86_64           2.2.0-1.el8                                  rhel-basos                94 k
 libipt                                x86_64           1.6.1-8.el8                                  rhel-appstream            50 k
 libkcapi                              x86_64           1.2.0-2.el8                                  rhel-basos                48 k
 libkcapi-hmaccalc                     x86_64           1.2.0-2.el8                                  rhel-basos                31 k
 libksba                               x86_64           1.3.5-7.el8                                  rhel-basos               135 k
 libmetalink                           x86_64           0.1.3-7.el8                                  rhel-basos                32 k
 libmount                              x86_64           2.32.1-24.el8                                rhel-basos               232 k
 libmpc                                x86_64           1.0.2-9.el8                                  rhel-appstream            59 k
 libnghttp2                            x86_64           1.33.0-3.el8_2.1                             rhel-basos                77 k
 libnsl2                               x86_64           1.2.0-2.20180605git4a062cf.el8               rhel-basos                58 k
 libpcap                               x86_64           14:1.9.1-4.el8                               rhel-basos               166 k
 libpkgconf                            x86_64           1.4.2-1.el8                                  rhel-basos                35 k
 libpsl                                x86_64           0.20.2-6.el8                                 rhel-basos                61 k
 libpwquality                          x86_64           1.4.0-9.el8                                  rhel-basos               103 k
 libseccomp                            x86_64           2.4.3-1.el8                                  rhel-basos                67 k
 libsecret                             x86_64           0.18.6-1.el8                                 rhel-basos               163 k
 libselinux                            x86_64           2.9-3.el8                                    rhel-basos               165 k
 libsemanage                           x86_64           2.9-3.el8                                    rhel-basos               165 k
 libsepol                              x86_64           2.9-1.el8                                    rhel-basos               339 k
 libsigsegv                            x86_64           2.11-5.el8                                   rhel-basos                30 k
 libsmartcols                          x86_64           2.32.1-24.el8                                rhel-basos               175 k
 libssh                                x86_64           0.9.4-2.el8                                  rhel-basos               215 k
 libssh-config                         noarch           0.9.4-2.el8                                  rhel-basos                18 k
 libstdc++                             x86_64           8.3.1-5.1.el8                                rhel-basos               451 k
 libstdc++-devel                       x86_64           8.3.1-5.1.el8                                rhel-appstream           2.0 M
 libtasn1                              x86_64           4.13-3.el8                                   rhel-basos                76 k
 libtirpc                              x86_64           1.1.4-4.el8                                  rhel-basos               113 k
 libtool-ltdl                          x86_64           2.4.6-25.el8                                 rhel-basos                58 k
 libunistring                          x86_64           0.9.9-3.el8                                  rhel-basos               422 k
 libusbx                               x86_64           1.0.23-4.el8                                 rhel-basos                74 k
 libutempter                           x86_64           1.1.6-14.el8                                 rhel-basos                32 k
 libuuid                               x86_64           2.32.1-24.el8                                rhel-basos                95 k
 libverto                              x86_64           0.3.0-5.el8                                  rhel-basos                24 k
 libxcrypt                             x86_64           4.1.1-4.el8                                  rhel-basos                73 k
 libxcrypt-devel                       x86_64           4.1.1-4.el8                                  rhel-basos                25 k
 libxml2                               x86_64           2.9.7-8.el8                                  rhel-basos               696 k
 libzstd                               x86_64           1.4.4-1.el8                                  rhel-basos               266 k
 lua-libs                              x86_64           5.3.4-11.el8                                 rhel-basos               118 k
 lz4-libs                              x86_64           1.8.3-2.el8                                  rhel-basos                66 k
 mpfr                                  x86_64           3.1.6-1.el8                                  rhel-basos               221 k
 ncurses                               x86_64           6.1-7.20180224.el8                           rhel-basos               387 k
 ncurses-base                          noarch           6.1-7.20180224.el8                           rhel-basos                81 k
 ncurses-libs                          x86_64           6.1-7.20180224.el8                           rhel-basos               335 k
 nettle                                x86_64           3.4.1-2.el8                                  rhel-basos               300 k
 npth                                  x86_64           1.5-4.el8                                    rhel-basos                26 k
 ocaml-srpm-macros                     noarch           5-4.el8                                      rhel-appstream           9.5 k
 openblas-srpm-macros                  noarch           2-2.el8                                      rhel-appstream           8.0 k
 openldap                              x86_64           2.4.46-15.el8                                rhel-basos               351 k
 openssl                               x86_64           1:1.1.1g-11.el8                              rhel-basos               706 k
 openssl-libs                          x86_64           1:1.1.1g-11.el8                              rhel-basos               1.5 M
 os-prober                             x86_64           1.74-6.el8                                   rhel-basos                51 k
 p11-kit                               x86_64           0.23.14-5.el8_0                              rhel-basos               272 k
 p11-kit-trust                         x86_64           0.23.14-5.el8_0                              rhel-basos               139 k
 pam                                   x86_64           1.3.1-11.el8                                 rhel-basos               738 k
 pcre                                  x86_64           8.42-4.el8                                   rhel-basos               208 k
 pcre2                                 x86_64           10.32-2.el8                                  rhel-basos               246 k
 perl-srpm-macros                      noarch           1-25.el8                                     rhel-appstream            11 k
 pkgconf                               x86_64           1.4.2-1.el8                                  rhel-basos                38 k
 pkgconf-m4                            noarch           1.4.2-1.el8                                  rhel-basos                17 k
 pkgconf-pkg-config                    x86_64           1.4.2-1.el8                                  rhel-basos                15 k
 platform-python                       x86_64           3.6.8-31.el8                                 rhel-basos                83 k
 platform-python-setuptools            noarch           39.2.0-6.el8                                 rhel-basos               632 k
 popt                                  x86_64           1.16-14.el8                                  rhel-basos                61 k
 procps-ng                             x86_64           3.3.15-3.el8                                 rhel-basos               328 k
 publicsuffix-list-dafsa               noarch           20180723-1.el8                               rhel-basos                56 k
 python-srpm-macros                    noarch           3-39.el8                                     rhel-appstream            14 k
 python3-libs                          x86_64           3.6.8-31.el8                                 rhel-basos               7.8 M
 python3-pip-wheel                     noarch           9.0.3-18.el8                                 rhel-basos               1.0 M
 python3-rpm-macros                    noarch           3-39.el8                                     rhel-appstream            13 k
 python3-setuptools-wheel              noarch           39.2.0-6.el8                                 rhel-basos               289 k
 qt5-srpm-macros                       noarch           5.12.5-3.el8                                 rhel-appstream            10 k
 readline                              x86_64           7.0-10.el8                                   rhel-basos               199 k
 redhat-release                        x86_64           8.3-1.0.el8                                  rhel-basos                41 k
 rpm                                   x86_64           4.14.3-4.el8                                 rhel-basos               541 k
 rpm-build-libs                        x86_64           4.14.3-4.el8                                 rhel-basos               154 k
 rpm-libs                              x86_64           4.14.3-4.el8                                 rhel-basos               338 k
 rust-srpm-macros                      noarch           5-2.el8                                      rhel-appstream           9.3 k
 setup                                 noarch           2.12.2-6.el8                                 rhel-basos               181 k
 sqlite-libs                           x86_64           3.26.0-11.el8                                rhel-basos               580 k
 systemd-libs                          x86_64           239-40.el8                                   rhel-basos               1.1 M
 systemd-pam                           x86_64           239-40.el8                                   rhel-basos               456 k
 systemd-udev                          x86_64           239-40.el8                                   rhel-basos               1.3 M
 trousers-lib                          x86_64           0.3.14-4.el8                                 rhel-basos               168 k
 tzdata                                noarch           2020a-1.el8                                  rhel-basos               469 k
 xkeyboard-config                      noarch           2.28-1.el8                                   rhel-appstream           782 k
 xml-common                            noarch           0.6.3-50.el8                                 rhel-basos                39 k
 xz                                    x86_64           5.2.4-3.el8                                  rhel-basos               153 k
 xz-libs                               x86_64           5.2.4-3.el8                                  rhel-basos                94 k
 zip                                   x86_64           3.0-23.el8                                   rhel-basos               270 k
 zlib                                  x86_64           1.2.11-16.el8_2                              rhel-basos               102 k
 zstd                                  x86_64           1.4.4-1.el8                                  rhel-appstream           393 k
 cracklib-dicts                        x86_64           2.9.6-15.el8                                 rhel-basos               4.0 M
 crypto-policies-scripts               noarch           20200713-1.git51d1222.el8                    rhel-basos                67 k
 elfutils-debuginfod-client            x86_64           0.180-1.el8                                  rhel-basos                64 k
 gnupg2-smime                          x86_64           2.2.20-2.el8                                 rhel-basos               283 k
 grubby                                x86_64           8.40-41.el8                                  rhel-basos                49 k
 hardlink                              x86_64           1:1.3-6.el8                                  rhel-basos                29 k
 kbd                                   x86_64           2.0.4-10.el8                                 rhel-basos               390 k
 kpartx                                x86_64           0.8.4-5.el8                                  rhel-basos               108 k
 libxkbcommon                          x86_64           0.9.1-1.el8                                  rhel-appstream           116 k
 memstrack                             x86_64           0.1.11-1.el8                                 rhel-basos                48 k
 openssl-pkcs11                        x86_64           0.4.10-2.el8                                 rhel-basos                66 k
 pigz                                  x86_64           2.4-4.el8                                    rhel-basos                79 k
 pinentry                              x86_64           1.1.0-2.el8                                  rhel-appstream           100 k
 platform-python-pip                   noarch           9.0.3-18.el8                                 rhel-basos               1.7 M
 redhat-release-eula                   x86_64           8.3-1.0.el8                                  rhel-basos                18 k
 shared-mime-info                      x86_64           1.9-3.el8                                    rhel-basos               329 k
 systemd                               x86_64           239-40.el8                                   rhel-basos               3.5 M
 trousers                              x86_64           0.3.14-4.el8                                 rhel-basos               153 k'''


rpm_info_list = rpm_info_list.split('\n')
for rpm_info in rpm_info_list:
    print(rpm_info.split()[0])